exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: "seminary.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
        exclude: '.history/.*'

  - repo: https://github.com/adityahase/black
    rev: 22.1.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        exclude: '.history/.*'

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        args: ["--config", ".github/helper/flake8.conf"]
        exclude: '.history/.*'

  - repo: https://github.com/pycqa/bandit
    rev: 1.9.3
    hooks:
      - id: bandit
        exclude: '.history/.*'
        args: ['''-r']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: '.history/.*|README.md'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
